version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: job_portal
    restart: always
    environment:
      POSTGRES_USER: company
      POSTGRES_PASSWORD: root
      POSTGRES_DB: job_portal_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: